### ISSUE TITLE
Drawer button motion

### ISSUE THREAD

**Issue by SourabhSNath** [slidenerd/Material-Design-Test-App#1]
Hello slidenerd, i had directly cloned the app and run it in android studio, but there is no animation for hamburger button, it doesn't turn when the drawer is opened or closed, it just becomes an arrow or the 3 lines according to the open or closing of the drawer. Can you check it?

**Comment by slidenerd** [comment]
which device? pre-lollipop or lollipop? or both?

**Comment by SourabhSNath** [comment]
On both, well after you updated your codes its normal now..

**Comment by slidenerd** [comment]
strange man , seriously! sometimes even i don't know what the hell is going
on with Android Studio [?][?][?]

On Thu, Dec 25, 2014 at 12:33 PM, Superblazer notifications@github.com
wrote:

> On both, well after you updated your codes its normal now..
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/slidenerd/Material-Design-Test-App/issues/1#issuecomment-68090850
> .

## 

Vivz,
_CEO & Founder of slidenerd.com http://slidenerd.com_
Let Intelligence Be Your Only Keyword
YouTube http://youtube.com/user/slidenerd/videos Facebook
http://facebook.com/slidenerd Twitter https://twitter.com/slidenerdtech
GitHub http://github.com/slidenerd Google+ http://google.com/+slidenerd

**Comment by slidenerd** [comment]
Hi! I’ve signed up for a spam filtering service called BitBounce and I added you to my “whitelist”. That means you can email me and your emails will come through.

For people who aren’t on my whilelist, I’m charging $0.05 in Bitcoin for their email to get to my inbox. A cleaner inbox and more money? Win! You should check it out!

Sign up to get paid for emails here: https://www.turing-cloud.com/bitbounce?ref=bitbounce

--

Unsubscribe from Slide Nerd's whitelist notification emails here: https://www.turing-cloud.com/unsubscribe_from_whitelist_email_notifications/3161784320
