### ISSUE TITLE
Hello can you make this app compatible with android versions above 8?

### ISSUE THREAD

**Issue by MelodyAustin** [slidenerd/Material-Design-Test-App#2]
I tried to make it modify and make it run on android 2.3.7, and it just didn't work... How can I get sliding tabs for lower android devices?

**Comment by slidenerd** [comment]
As per many big sites and resources now, dont go below API 11 anymore,
there are hardly 1% devices running them

On Wed, Jan 28, 2015 at 10:41 AM, MelodyAustin notifications@github.com
wrote:

> I tried to make it modify and make it run on android 2.3.7, and it just
> didn't work... How can I get sliding tabs for lower android devices?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/slidenerd/Material-Design-Test-App/issues/2.

## 

Vivz,
_CEO & Founder of slidenerd.com http://slidenerd.com_
Let Intelligence Be Your Only Keyword
YouTube http://youtube.com/user/slidenerd/videos Facebook
http://facebook.com/slidenerd Twitter https://twitter.com/slidenerdtech
GitHub http://github.com/slidenerd Google+ http://google.com/+slidenerd
