### ISSUE TITLE
Setting Navigation Drawer Width

### ISSUE THREAD

**Issue by SourabhSNath** [slidenerd/Material-Design-Test-App#3]
Hello Slidenerd, 
Check this out, 
http://stackoverflow.com/a/26769452/4273056

It works perfectly!

**Comment by slidenerd** [comment]
thank you very much for sharing this [?][?][?]

On Thu, Jan 29, 2015 at 7:54 PM, Superblazer notifications@github.com
wrote:

> Hello Slidenerd,
> Check this out,
> http://stackoverflow.com/a/26769452/4273056
> 
> It works perfectly!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/slidenerd/Material-Design-Test-App/issues/3.

## 

Vivz,
_CEO & Founder of slidenerd.com http://slidenerd.com_
Let Intelligence Be Your Only Keyword
YouTube http://youtube.com/user/slidenerd/videos Facebook
http://facebook.com/slidenerd Twitter https://twitter.com/slidenerdtech
GitHub http://github.com/slidenerd Google+ http://google.com/+slidenerd

**Comment by SourabhSNath** [comment]
You are welcome :D
